### ISSUE TITLE
Doesnt seem to be working on Mac Os after Ventura update.

### ISSUE THREAD

**Issue by CodingWithDavidZ** [Corcules/KMlink#12]
When pressing the button before Ventura, it worked as expected. After Ventura update, it doesn't work. When setting up a button it still finds the macros, it just won't execute them when the button is pressed.

**Comment by CodingWithDavidZ** [comment]
Update, downloading it directly and installing the plugin works fine, the one on Stream Deck Store does not work.

**Comment by mfoxde** [comment]
Same issue here. I'm on Ventura running on Apple Silicon. I tried to uninstall the stream deck version and install it directly like you suggested, but unfortunately no change here.

I can see the list of macros, but trying to trigger the macro is not doing anything.

**Comment by Corcules** [comment]
Hi, 

As the StreamDeck Store just get the last release of the plugin from Github automatically, the plugin is exactly the same both ways...

Some people report issue with security preferences with Ventura, specially when upgrading a previous OS.
That's why uninstall > reinstall may help.

You may check and/or reset your system preferences (as "Privacy and Security", background execution app, disk access, ...).Streamdeck app need to be able to control Keyboard Maestro. Keyboard Maestro Engine need to run in background,... 

Others resolved the issue by a permissions repair.

I don't have upgrade to Ventura yet so i cannot help you more at this time

Please let me know here if you find a solution, this can help others... ;-)
