### ISSUE TITLE
Search field in Macro picker?

### ISSUE THREAD

**Issue by lloydi** [Corcules/KMlink#17]
I have a *LOT* of Macros, and finding the right macro can sometimes be a challenge. Also, the sort order for folders differs from how it is in KM and how they are exposed in KMLink.

A search input in the picker would be a killer feature and would make finding Macros so much more straightforward.

**Comment by Corcules** [comment]
Hi,

KMLink give you 2 ways to find a macro:
- the last edited macro in KM will be at first position in the list.
- as a standard select element, you can type few letters when the list is open.

Yes a search input might be usefull but because i think the 2 ways above are enough 90% of the time and because i don't want to overload the plugin, i guess i will not add a search.
