### ISSUE TITLE
Suggestion: Sort Groups Alphabetically

### ISSUE THREAD

**Issue by sylumer** [Corcules/KMlink#4]
I'm finding it cumbersome to track down particular macros in the Macro list. I have quite a few macro groups to help me organise my library of Keyboard Maestro macros, and the display in the Stream Deck plugin sorts alphabetically within each macro group, but the macro groups are not listed alphabetically.

I'd therefore like to suggest that the macro selection list is changed to sort the macros alphabetically to help with searching.

Thanks for any consideration on this suggestion.

Regards,

Stephen.

**Comment by Corcules** [comment]
Well, thank for your suggestion, but some people ask me for that, others ask for another order...

Now, the macro list on SD action reflect the list of KM, by default.
I don't want to do more parsing, reorder, add sort option or .... to keep the best performance and efficiency as possible. Setting an action key on SD should be as quick as possible. 

That's why i just added the last modified macro on the top of the list which is the best compromis for the main workflow : prepare the macro in KM, switch to SD app, add a key with the first macro on the list. Quick.

Be sure to run the last version of kmlink for the last modified macro on top.

If you can't find your macro easily, just open it on KM, eventually save it without any modification and it would be on the top of the macro list in SD.
